plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def dashboardKeystorePropertiesFile = rootProject.file('../ex30dashboard/keystore.properties')
def dashboardKeystoreProperties = new Properties()
if (dashboardKeystorePropertiesFile.exists()) {
    dashboardKeystoreProperties.load(new FileInputStream(dashboardKeystorePropertiesFile))
}
def dashboardKeystoreRoot = rootProject.file('../ex30dashboard')

android {
    namespace 'com.kadireren.ex30sensorlab'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kadireren.ex30sensorlab'
        minSdk 30
        targetSdk 35
        versionCode 12
        versionName '1.0.11'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    signingConfigs {
        release {
            if (dashboardKeystorePropertiesFile.exists()) {
                storeFile dashboardKeystoreRoot.toPath().resolve(dashboardKeystoreProperties['storeFile']).toFile()
                storePassword dashboardKeystoreProperties['storePassword']
                keyAlias dashboardKeystoreProperties['keyAlias']
                keyPassword dashboardKeystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (dashboardKeystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    useLibrary 'android.car'
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
